### ISSUE TITLE
只支持上传，不支持删除，那随着部署次数的增多，垃圾文件不是越来越多？

### ISSUE THREAD

**Issue by zhangolve** [takashiki/cos-webpack#2]
如题

**Comment by takashiki** [comment]
是的，不过一方面开发调试阶段生成的文件可以配置成不上传，所以对于个人项目来说正式环境上传的文件数量一般不会特别多；另一方面删除之前的文件好像除了制定文件夹内的内容全部删之外好像也没什么好的方案，但实际上在上线新服务时，一般是资源文件先上线，再更新页面文件，老版本的资源需要在一段时间内共存，所以最好还是不删老版本资源文件比较好。
